export const COUNTRY_ACTION_TYPES = {
  SET_COUNTRIES: "SET_COUNTRIES/countries",
  SET_COUNTRIES_FILTER: "SET_COUNTRIES_FILTER/countries",
  SET_COUNTRY_TO_DISPLAY: "SET_COUNTRY_TO_DISPLAY/country",
  SET_COUNTRY_MEMO: "SET_COUNTRY_MEMO/country",
};
